version: '2'
services:
    trafalbar-app:
        image: trafalbar
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://trafalbar-postgresql:5432/Trafalbar
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trafalbar-postgresql:
        extends:
            file: postgresql.yml
            service: trafalbar-postgresql
